import { prisma } from "@/lib/prisma";

// ── Lifetime Free Email Domains ──────────────────────────────────────────────
// Users with LinkedIn accounts from these email domains get a permanent free
// subscription. They are never charged and never see subscription/trial prompts.
const LIFETIME_FREE_DOMAINS = ["testriq.com", "cinutedigital.com"];

// ── Watermark ────────────────────────────────────────────────────────────────
// Appended to every post for trial users and lifetime-free-domain users.
// Paid subscribers and admins do NOT get the watermark.
export const WATERMARK_TEXT = "Post generated by Kruti.io\nhttps://kruti.io/";

/**
 * Check if an email qualifies for lifetime free subscription.
 * Matches @testriq.com and @cinutedigital.com domains (case-insensitive).
 */
export function isLifetimeFreeEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  const domain = email.toLowerCase().split("@")[1];
  return LIFETIME_FREE_DOMAINS.includes(domain);
}

/**
 * Determine if a user's posts should include the Kruti.io watermark.
 *
 * Watermark applies to:
 *   - Trial users (status = "trialing")
 *   - Lifetime free domain users (@testriq.com, @cinutedigital.com)
 *
 * NO watermark for:
 *   - Paid subscribers (status = "active" via Razorpay)
 *   - Admins (role = "admin")
 */
export function shouldShowWatermark({
  subscriptionStatus,
  email,
  role,
}: {
  subscriptionStatus: string | null | undefined;
  email: string | null | undefined;
  role: string | null | undefined;
}): boolean {
  // Admins never get watermark
  if (role === "admin") return false;

  // Lifetime free domain users always get watermark
  if (isLifetimeFreeEmail(email)) return true;

  // Trial users get watermark
  if (subscriptionStatus === "trialing") return true;

  // Paid subscribers (active, cancel_pending) do NOT get watermark
  return false;
}

/**
 * Ensure a qualifying user has an active lifetime subscription.
 * Creates or upgrades their subscription to active with a far-future expiry.
 * Returns true if a subscription was created/upgraded, false if already active.
 */
export async function ensureLifetimeSubscription(userId: string): Promise<boolean> {
  const existing = await prisma.subscription.findUnique({
    where: { userId },
  });

  // Already has an active lifetime subscription - nothing to do
  if (existing?.status === "active" && existing.currentPeriodEnd &&
      existing.currentPeriodEnd >= new Date("2090-01-01")) {
    return false;
  }

  // Create or upgrade to lifetime active subscription
  await prisma.subscription.upsert({
    where: { userId },
    create: {
      userId,
      status: "active",
      currency: "INR",
      currentPeriodEnd: new Date("2099-12-31T23:59:59Z"),
      trialEnd: null,
      trialRemindersSent: "",
      postsGeneratedThisCycle: 0,
    },
    update: {
      status: "active",
      currentPeriodEnd: new Date("2099-12-31T23:59:59Z"),
      trialEnd: null,
      trialRemindersSent: "",
    },
  });

  console.log(`[Lifetime] Granted lifetime free subscription to user ${userId}`);
  return true;
}

/**
 * Check if a user has an active subscription that allows content generation.
 * Returns allowed: false for expired trials, canceled, unpaid, or missing subscriptions.
 */
export async function checkActiveSubscription(userId: string): Promise<{
  allowed: boolean;
  reason?: string;
}> {
  // Super admins get lifetime access - bypass all subscription checks
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { role: true, email: true },
  });
  if (user?.role === "admin") {
    return { allowed: true };
  }

  // Lifetime free email domains - bypass all subscription checks
  if (isLifetimeFreeEmail(user?.email)) {
    // Ensure they have an active subscription record (auto-fix if somehow missing/expired)
    await ensureLifetimeSubscription(userId);
    return { allowed: true };
  }

  let sub = await prisma.subscription.findUnique({
    where: { userId },
  });

  if (!sub) {
    const trialEnd = new Date();
    trialEnd.setDate(trialEnd.getDate() + 7);
    try {
      sub = await prisma.subscription.create({
        data: {
          userId,
          status: "trialing",
          trialEnd,
          currency: "INR",
        },
      });
    } catch (err) {
      console.error("Failed to auto-create trial subscription in check:", err);
      return { allowed: false, reason: "No subscription found and failed to create one. Please try again or contact support." };
    }
  }

  if (sub.status === "active" || sub.status === "cancel_pending") {
    return { allowed: true };
  }

  if (sub.status === "trialing") {
    if (sub.trialEnd && sub.trialEnd < new Date()) {
      return {
        allowed: false,
        reason: "Your free trial has ended. Subscribe to continue creating content.",
      };
    }
    return { allowed: true };
  }

  return { allowed: false, reason: "Your subscription is not active. Please subscribe to continue." };
}
